"""Add storeUsername to YourModelName

Revision ID: 97bfb4f7faea
Revises: 4bf025122685
Create Date: 2025-05-04 14:49:04.776792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97bfb4f7faea'
down_revision = '4bf025122685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storeUsername', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['storeUsername'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('storeUsername')

    # ### end Alembic commands ###
