import React from 'react';

export default function ReportContent() {
  const reports = [
    { id: 'RPT001', title: 'Monthly Sales', date: 'Apr 01, 2025', generatedBy: 'Admin', status: 'Completed' },
    { id: 'RPT002', title: 'Refund Summary', date: 'Apr 05, 2025', generatedBy: 'Manager', status: 'In Progress' },
    { id: 'RPT003', title: 'Customer Feedback', date: 'Apr 10, 2025', generatedBy: 'Support', status: 'Completed' },
  ];

  const summaryStats = [
    { label: 'Reports Generated', value: 42 },
    { label: 'Completed', value: 36 },
    { label: 'Pending', value: 6 },
  ];

  return (
    <div className="w-full">
      {/* Header */}
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-gray-800 dark:text-white">Reports</h2>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4 mb-6">
        {summaryStats.map((stat, index) => (
          <div key={index} className="bg-white dark:bg-gray-800 rounded-xl shadow p-4">
            <h4 className="text-sm font-medium text-gray-600 dark:text-gray-400">{stat.label}</h4>
            <p className="text-2xl font-bold text-gray-800 dark:text-white">{stat.value}</p>
          </div>
        ))}
      </div>

      {/* Report Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {reports.map((report, idx) => (
          <div key={idx} className="bg-white dark:bg-gray-800 p-4 rounded-xl shadow hover:shadow-md transition">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">{report.title}</h3>
            <p className="text-sm text-gray-600 dark:text-gray-400"><strong>ID:</strong> {report.id}</p>
            <p className="text-sm text-gray-600 dark:text-gray-400"><strong>Date:</strong> {report.date}</p>
            <p className="text-sm text-gray-600 dark:text-gray-400"><strong>Generated By:</strong> {report.generatedBy}</p>
            <span className={`inline-block mt-2 px-2 py-1 text-xs rounded-full font-semibold ${
              report.status === 'Completed' ? 'bg-green-100 text-green-700' :
              'bg-yellow-100 text-yellow-700'
            }`}>
              {report.status}
            </span>
          </div>
        ))}
        {reports.length === 0 && (
          <div className="col-span-full text-center text-gray-400 dark:text-gray-500 py-4">
            No reports available.
          </div>
        )}
      </div>
    </div>
  );
}
